version: '2'

networks:
  ecodices_network:
    external:
      name: nginxproxynetwork

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: ecodices_tmp_es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true
    volumes:
      - eco_tmp_es:/usr/share/elasticsearch/data
      - /home/robz/:/home
    networks:
      - ecodices_network

  pyservice:
    image: registry.diginfra.net/tsd/ecodices-service:0.9
    container_name: ecodices_tmp_service
    environment:
      - VIRTUAL_HOST=tmpecoservice.sd.di.huc.knaw.nl
    expose:
      - 5000
    volumes:
      - /home/robz/:/home
      - ecoxml_tmp:/xml
    networks:
      - ecodices_network